spring.application.name=HotelManagementFrontend
<<<<<<< HEAD
backend.base-url=http://localhost:8085/api
=======
backend.base-url=${BACKEND_URL}
>>>>>>> 4b5bb53eee5d3d365406b35b8ed31ffe4ef2bf23
server.port=8089